### ISSUE TITLE
Inspecting fetch URL and options

### ISSUE THREAD

**Issue by robcaldecott** [jefflau/jest-fetch-mock#55]
When testing it would sometimes be useful to inspect the fetch URL and options being passed: checking for the correct headers, POST body content, etc. Is there any way to achieve this using `jest-fetch-mock`?

**Comment by jefflau** [comment]
Hi @robcaldecott 

`jest-fetch-mock` does support it because the jest mocks underlying architecture supports it. I probably need to document it better, but it works the same way jest mocks work. You can copy these two files `api.js` and `api.test.js` into your project to see how it works. The docs for mocks in jest are here: [https://facebook.github.io/jest/docs/en/mock-functions.html](https://facebook.github.io/jest/docs/en/mock-functions.html)

```js

```
import 'isomorphic-fetch';

export function getStuff() {
  return fetch('https://facebook.com').then(stuff => {
    console.log(stuff);
  });
}
```js
import { getStuff } from './api';

it('mock test', () => {
  const mock = fetch.mockResponse(JSON.stringify({ access_token: '12345' }));
  getStuff();

  console.log(fetch.mock.calls);

  expect(fetch.mock.calls.length).toEqual(1);
  expect(fetch.mock.calls[0][0]).toEqual('https://facebook.com');

  fetch.resetMocks();

  console.log(fetch.mock.calls);
});

```

**Comment by robcaldecott** [comment]
Of course. I should have worked that out. :)
Many thanks! Works perfectly.

**Comment by jefflau** [comment]
Cool :)

Sorry for the slow reply. Hope it works good now!

I'll leave this issue up until I get the documentation sorted out

**Comment by jefflau** [comment]
Added documentation to this so hopefully it won't be an issue. Closing this!
